import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const inter = localFont({
  src: "./fonts/inter.ttf",
  weight: "400",
  variable: "--font-inter"
})

const playfair = localFont({
  src: "./fonts/PlayfairDisplay.ttf",
  weight: "300",
  variable: "--font-playfair"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
